version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-microservice
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  api-gateway:
    build:
      context: ./api-gateway-microservice
    container_name: api-gateway
    ports:
      - "8000:8080"
    depends_on:
      - auth-service
      - business-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  business-service:
    build:
      context: ./business-data-service
    container_name: business-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoice_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
